language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk7

matrix:
  include:
  - scala: 2.12.1
    jdk: oraclejdk8

script:
  - "sbt clean coverage test"
  - "sbt coverageAggregate"

after_success: "sbt coveralls"