language: scala

scala:
  - 2.11.12

jdk:
  - oraclejdk7

matrix:
  include:
  - scala: 2.12.7
    jdk: oraclejdk8

script:
  - "sbt scoverage"
  - "sbt coverageAggregate"
  - "sbt checkFormatting"

after_success: "sbt coveralls"