language: scala

scala:
  - 2.11.11

jdk:
  - oraclejdk7

matrix:
  include:
  - scala: 2.12.3
    jdk: oraclejdk8

script:
  - "sbt scoverage"
  - "sbt coverageAggregate"

after_success: "sbt coveralls"