name: build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jvm:
          - temurin-jre:1.17.0.7
          - graalvm-java11:22.3.2
          - zulu:8.0.372
        os:
          - ubuntu-latest
      fail-fast: false
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.jvm }}
      - name: Compile, test and check format, coverage
        run: "sbt -batch clean checkFormatting +test scoverage"
        shell: bash